//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DomainModel {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BalanceState {
        
        private DocumentIdentification_type documentIdentificationField;
        
        private EICIdentification_type senderIdentificationField;
        
        private EICIdentification_type receiverIdentificationField;
        
        private DocumentDateTime_type documentDateTimeField;
        
        private Added_type addedField;
        
        private Removed_type removedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentIdentification_type DocumentIdentification {
            get {
                return this.documentIdentificationField;
            }
            set {
                this.documentIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EICIdentification_type SenderIdentification {
            get {
                return this.senderIdentificationField;
            }
            set {
                this.senderIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EICIdentification_type ReceiverIdentification {
            get {
                return this.receiverIdentificationField;
            }
            set {
                this.receiverIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentDateTime_type DocumentDateTime {
            get {
                return this.documentDateTimeField;
            }
            set {
                this.documentDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Added_type Added {
            get {
                return this.addedField;
            }
            set {
                this.addedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Removed_type Removed {
            get {
                return this.removedField;
            }
            set {
                this.removedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocumentIdentification_type {
        
        private string vField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Removed_type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Added_type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BalancePointsList_type {
        
        private BalancePoint_type[] balancePointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BalancePoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BalancePoint_type[] BalancePoint {
            get {
                return this.balancePointField;
            }
            set {
                this.balancePointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BalancePoint_type {
        
        private EICIdentification_type meteringPointIdentificationField;
        
        private EICIdentification_type gridOperatorIdentificationField;
        
        private EICIdentification_type openSupplierBalanceProviderIdentificationField;
        
        private EICIdentification_type gridOperatorBalanceProviderIdentificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EICIdentification_type MeteringPointIdentification {
            get {
                return this.meteringPointIdentificationField;
            }
            set {
                this.meteringPointIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EICIdentification_type GridOperatorIdentification {
            get {
                return this.gridOperatorIdentificationField;
            }
            set {
                this.gridOperatorIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EICIdentification_type OpenSupplierBalanceProviderIdentification {
            get {
                return this.openSupplierBalanceProviderIdentificationField;
            }
            set {
                this.openSupplierBalanceProviderIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EICIdentification_type GridOperatorBalanceProviderIdentification {
            get {
                return this.gridOperatorBalanceProviderIdentificationField;
            }
            set {
                this.gridOperatorBalanceProviderIdentificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EICIdentification_type {
        
        private string vField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Removed_type : BalancePointsList_type {
        
        private System.DateTime lastDateField;
        
        private bool lastDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime lastDate {
            get {
                return this.lastDateField;
            }
            set {
                this.lastDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastDateSpecified {
            get {
                return this.lastDateFieldSpecified;
            }
            set {
                this.lastDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Added_type : BalancePointsList_type {
        
        private System.DateTime firstDateField;
        
        private bool firstDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime firstDate {
            get {
                return this.firstDateField;
            }
            set {
                this.firstDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstDateSpecified {
            get {
                return this.firstDateFieldSpecified;
            }
            set {
                this.firstDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocumentDateTime_type {
        
        private System.DateTime vField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime v {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
    }
}
