//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EnergyReportResult {
    
    private DocumentIdentification_type documentIdentificationField;
    
    private EICIdentification_type senderIdentificationField;
    
    private EICIdentification_type receiverIdentificationField;
    
    private DocumentDateTime_type documentDateTimeField;
    
    private DocumentIdentification_type originalDocumentIdentificationField;
    
    private AccountTimeSeries_type[] accountTimeSeriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentIdentification_type DocumentIdentification {
        get {
            return this.documentIdentificationField;
        }
        set {
            this.documentIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type SenderIdentification {
        get {
            return this.senderIdentificationField;
        }
        set {
            this.senderIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type ReceiverIdentification {
        get {
            return this.receiverIdentificationField;
        }
        set {
            this.receiverIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentDateTime_type DocumentDateTime {
        get {
            return this.documentDateTimeField;
        }
        set {
            this.documentDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentIdentification_type OriginalDocumentIdentification {
        get {
            return this.originalDocumentIdentificationField;
        }
        set {
            this.originalDocumentIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AccountTimeSeries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AccountTimeSeries_type[] AccountTimeSeries {
        get {
            return this.accountTimeSeriesField;
        }
        set {
            this.accountTimeSeriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentIdentification_type {
    
    private string vField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AccountTimeSeries_type {
    
    private EICIdentification_type accountingPointField;
    
    private string resultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type AccountingPoint {
        get {
            return this.accountingPointField;
        }
        set {
            this.accountingPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EICIdentification_type {
    
    private string vField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentDateTime_type {
    
    private System.DateTime vField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
}
