//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NotifySupplyAgreement {
    
    private DocumentIdentification_type documentIdentificationField;
    
    private EICIdentification_type senderIdentificationField;
    
    private EICIdentification_type receiverIdentificationField;
    
    private DocumentDateTime_type documentDateTimeField;
    
    private EICIdentification_type openSupplierIdentificationField;
    
    private EICIdentification_type customerIdentificationField;
    
    private System.DateTime firstDateField;
    
    private System.DateTime lastDateField;
    
    private bool lastDateFieldSpecified;
    
    private NotifySupplyAgreementReason_type reasonField;
    
    private bool reasonFieldSpecified;
    
    private EICIdentification_type[] meteringPointIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentIdentification_type DocumentIdentification {
        get {
            return this.documentIdentificationField;
        }
        set {
            this.documentIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type SenderIdentification {
        get {
            return this.senderIdentificationField;
        }
        set {
            this.senderIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type ReceiverIdentification {
        get {
            return this.receiverIdentificationField;
        }
        set {
            this.receiverIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DocumentDateTime_type DocumentDateTime {
        get {
            return this.documentDateTimeField;
        }
        set {
            this.documentDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type OpenSupplierIdentification {
        get {
            return this.openSupplierIdentificationField;
        }
        set {
            this.openSupplierIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type CustomerIdentification {
        get {
            return this.customerIdentificationField;
        }
        set {
            this.customerIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FirstDate {
        get {
            return this.firstDateField;
        }
        set {
            this.firstDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime LastDate {
        get {
            return this.lastDateField;
        }
        set {
            this.lastDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastDateSpecified {
        get {
            return this.lastDateFieldSpecified;
        }
        set {
            this.lastDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NotifySupplyAgreementReason_type Reason {
        get {
            return this.reasonField;
        }
        set {
            this.reasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReasonSpecified {
        get {
            return this.reasonFieldSpecified;
        }
        set {
            this.reasonFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeteringPointIdentification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EICIdentification_type[] MeteringPointIdentification {
        get {
            return this.meteringPointIdentificationField;
        }
        set {
            this.meteringPointIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentIdentification_type {
    
    private string vField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentDateTime_type {
    
    private System.DateTime vField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EICIdentification_type {
    
    private string vField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum NotifySupplyAgreementReason_type {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GRID AGREEMENT ENDED")]
    GRIDAGREEMENTENDED,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GRID AGREEMENT RESTORED")]
    GRIDAGREEMENTRESTORED,
}
